tasks:
<<<<<<< HEAD
  - init: npm install && npm run build
=======
  - name: npm install
    init: npm install
  - name: npm run build
    init: npm run build
>>>>>>> 32360549830e84a9919fe832973bdfee52e376d2

vscode:
  extensions:
    - bradlc.vscode-tailwindcss@0.5.8:V9S7Nn0g1hYglki98ko+YA==
    - ecmel.vscode-html-css@1.9.1:IxAxIfaC6OW70vfl5VyKbg==
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==