tasks:
  - name: npm install
    init: npm install
  - name: npm run build
    init: npm run build

vscode:
  extensions:
    - bradlc.vscode-tailwindcss@0.5.8:V9S7Nn0g1hYglki98ko+YA==
    - ecmel.vscode-html-css@1.9.1:IxAxIfaC6OW70vfl5VyKbg==
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
    - eamodio.gitlens@11.1.3:3tXZCqyi6cUbAZjnx1jPSA==